In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pickle

In [10]:
import sklearn.linear_model as sk
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score

from sklearn.ensemble import RandomForestClassifier

from sklearn.svm import SVC

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import GradientBoostingClassifier

In [11]:
data = pd.read_csv("heart.csv")

In [12]:
x = data.drop(["target"], axis=1)
y = data["target"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


# Logistic Regression

In [14]:
lor = sk.LogisticRegression()

In [15]:
lor.fit(x_train, y_train)

C:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
835   49    1   2       118   149    0        0      126      0      0.8   
137   64    0   0       180   325    0        1      154      1      0.0   
534   54    0   2       108   267    0        0      167      0      0.0   
495   59    1   0       135   234    0        1      161      0      0.5   
244   51    1   2       125   245    1        0      166      0      2.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
700   41    1   2       130   214    0        0      168      0      2.0   
71    61    1   0       140   207    0        0      138      1      1.9   
106   51    1   0       140   299    0        1      173      1      1.6   
270   43    1   0       110   211    0        1      161      0      0.0   
860   52    1   0       112   230    0        1      160      0      0.0   

     slope  ca  thal  
835      2   3     2  
137      2   0     2  
534      2   0     2  
495      1   0     3  
244      1   0     2  
..     ...  ..   ...  
700      1   0     2  
71       2   1     3  
106      2   0     3  
270      2   0     3  
860      2   1     2  

[820 rows x 13 columns]

In [17]:
y_train

835    0
137    1
534    1
495    1
244    1
      ..
700    1
71     0
106    0
270    1
860    0
Name: target, Length: 820, dtype: int64

In [18]:
y_pred = lor.predict(x_test)

In [19]:
accuracy_score(y_test, y_pred)

0.7853658536585366

In [20]:
confusion_matrix(y_test, y_pred)

array([[71, 31],
       [13, 90]], dtype=int64)

In [21]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.7849324195697696
f1 score:  0.8035714285714285


In [22]:
with open("logisticregression.pkl", "wb") as f:
    pickle.dump(lor, f)

# Random Forest Classifier

In [23]:
rf = RandomForestClassifier()

In [24]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [25]:
y_pred = rf.predict(x_test)

In [26]:
accuracy_score(y_test, y_pred)

0.9853658536585366

In [27]:
confusion_matrix(y_test, y_pred)

array([[102,   0],
       [  3, 100]], dtype=int64)

In [28]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.9854368932038835
f1 score:  0.9852216748768473


In [29]:
with open("randomforest.pkl", "wb") as f:
    pickle.dump(rf, f)

# Support Vector Machine - Linear Kernel

In [30]:
svm = SVC(kernel='linear')

In [33]:
svm.fit(x_train, y_train)

SVC(kernel='linear')

In [34]:
y_pred = svm.predict(x_test)

In [35]:
accuracy_score(y_test, y_pred)

0.8048780487804879

In [36]:
confusion_matrix(y_test, y_pred)

array([[72, 30],
       [10, 93]], dtype=int64)

In [37]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.8043974871501998
f1 score:  0.8230088495575221


In [39]:
with open("svmlinear.pkl", "wb") as f:
    pickle.dump(svm, f)

# Support Vector Machine - Gaussian Kernel

In [40]:
svm = SVC(kernel='rbf')

In [41]:
svm.fit(x_train, y_train)

SVC()

In [42]:
'rbf', 'poly', 'precomputed', 'linear', 'sigmoid'

('rbf', 'poly', 'precomputed', 'linear', 'sigmoid')

In [43]:
y_pred = svm.predict(x_test)

In [44]:
accuracy_score(y_test, y_pred)

0.6829268292682927

In [45]:
confusion_matrix(y_test, y_pred)

array([[62, 40],
       [25, 78]], dtype=int64)

In [46]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.6825623453264802
f1 score:  0.7058823529411764


In [48]:
with open("svmrbf.pkl", "wb") as f:
    pickle.dump(svm, f)

# Support Vector Machine - Polynomial Kernel

In [49]:
svm = SVC(kernel='poly')

In [50]:
svm.fit(x_train, y_train)

SVC(kernel='poly')

In [51]:
y_pred = svm.predict(x_test)

In [52]:
accuracy_score(y_test, y_pred)

0.6682926829268293

In [53]:
confusion_matrix(y_test, y_pred)

array([[66, 36],
       [32, 71]], dtype=int64)

In [54]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.6681896059394631
f1 score:  0.6761904761904761


In [56]:
with open("svmpoly.pkl", "wb") as f:
    pickle.dump(svm, f)

# Support Vector Machine - Sigmoid Kernel

In [57]:
svm = SVC(kernel='sigmoid')

In [58]:
svm.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [59]:
y_pred = svm.predict(x_test)

In [60]:
accuracy_score(y_test, y_pred)

0.4926829268292683

In [61]:
confusion_matrix(y_test, y_pred)

array([[47, 55],
       [49, 54]], dtype=int64)

In [62]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.4925280791928422
f1 score:  0.5094339622641509


In [63]:
with open("svmsigmoid.pkl", "wb") as f:
    pickle.dump(svm, f)

# K Nearest Neighbour

In [64]:
knn = KNeighborsClassifier()

In [65]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [66]:
y_pred = knn.predict(x_test)

In [67]:
accuracy_score(y_test, y_pred)

0.7317073170731707

In [68]:
confusion_matrix(y_test, y_pred)

array([[74, 28],
       [27, 76]], dtype=int64)

In [69]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.7316771368741672
f1 score:  0.7342995169082126


In [70]:
with open("knn.pkl", "wb") as f:
    pickle.dump(knn, f)

# Naive Bayes

In [71]:
nb = GaussianNB()

In [72]:
nb.fit(x_train, y_train)

GaussianNB()

In [73]:
y_pred = nb.predict(x_test)

In [74]:
accuracy_score(y_test, y_pred)

0.8

In [75]:
confusion_matrix(y_test, y_pred)

array([[72, 30],
       [11, 92]], dtype=int64)

In [76]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.7995431182181609
f1 score:  0.8177777777777777


In [77]:
with open("naivebayes.pkl", "wb") as f:
    pickle.dump(nb, f)

# Decision Tree Classifier

In [78]:
dt = DecisionTreeClassifier()

In [79]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [80]:
y_pred = dt.predict(x_test)

In [81]:
accuracy_score(y_test, y_pred)

0.9853658536585366

In [82]:
confusion_matrix(y_test, y_pred)

array([[102,   0],
       [  3, 100]], dtype=int64)

In [83]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.9854368932038835
f1 score:  0.9852216748768473


In [84]:
with open("decisiontree.pkl", "wb") as f:
    pickle.dump(dt, f)

# Gradient Boosting Classifier

In [85]:
gbc = GradientBoostingClassifier()

In [86]:
gbc.fit(x_train, y_train)

GradientBoostingClassifier()

In [87]:
y_pred = gbc.predict(x_test)

In [88]:
accuracy_score(y_test, y_pred)

0.9317073170731708

In [89]:
confusion_matrix(y_test, y_pred)

array([[93,  9],
       [ 5, 98]], dtype=int64)

In [90]:
print("roc_auc_score: ", roc_auc_score(y_test, y_pred))
print("f1 score: ", f1_score(y_test, y_pred))

roc_auc_score:  0.9316105082809822
f1 score:  0.9333333333333335


In [91]:
with open("gradientboost.pkl", "wb") as f:
    pickle.dump(gbc, f)